BATCHSIZE=${6}
INDEX=${1}
FILE=${2}
MODEL_DIR=${3}
THRESHOLD=${4}
EXPERIMENT_NAME=${5}
echo "EXPERIMENT NAME ${EXPERIMENT_NAME}"
START=$(($((INDEX * BATCHSIZE)) + 1))
END=$(($START + BATCHSIZE))
SAMPLED_SMILES=${FILE}_${INDEX}_sampled_smiles.txt
sed -n "$START,${END}p;$(($END + 1))q" $FILE > $SAMPLED_SMILES
echo "N lines in SAMPLED_SMILES"
wc -l $SAMPLED_SMILES
python run_chemprop.py $SAMPLED_SMILES $START $FILE $MODEL_DIR $THRESHOLD $EXPERIMENT_NAME
rm $SAMPLED_SMILES
echo nice_jobdone
